import type { NextPage } from "next";
import Head from "next/head";
import Footer from "../blocks/Footer";
import Header from "../blocks/Header";
import Menu from "../blocks/Menu";

import Contacts from "../blocks/Contacts";
import Providers from "../blocks/Providers";

import { isAbsoluteUrl } from "next/dist/shared/lib/utils";

const Home: NextPage = ({ providersTabs }) => {
  return (
    <>
      {" "}
      <div>
        <Head>
          <title>Lugacom</title>
          <meta name="description" content="Generated by create next app" />
        </Head>

        <Menu />
        <Header />

        <Providers tabs={providersTabs} />

        {/* <Contacts /> */}

        {/* <Footer /> */}
      </div>
    </>
  );
};

export default Home;
export async function getServerSideProps() {
  const res = await fetch("http://10.200.52.9:1337/api/providers?populate=*");

  const { data: providersTabs } = await res.json();

  return {
    props: {
      providersTabs,
    },
  };
}
